### ISSUE TITLE
OS101 Module 4 Lesson 1: distinction between Operational and Infrastructure Softwares unclear

### ISSUE THREAD

**Issue by lauracion** [nasa/Transform-to-Open-Science#647] opened 2024-02-05 16:46 UTC
The definitions for operational and infrastructure software are the same except for the words "operational" and "infrastructure" [here](https://github.com/nasa/Transform-to-Open-Science/blob/main/docs/Area2_Capacity_Sharing/Open-Science-101/modules/Module_4/Lesson_1/readme.md). 

Also, both have Fprime as an example, so the examples did not help me understand what is the difference between the two types of software.

**Comment by katblanchette** [comment] 2024-07-02 21:50
@bressler95tops - Is this a similar PR to #710 and #766?

**Comment by katblanchette** [comment] 2024-07-02 21:50
Thank you @lauracion for your comment. We are working to get this resolved.

**Comment by bressler95tops** [comment] 2024-07-02 21:53
Good catch @katblanchette that does appear to be a duplicate of Issue #710, PR #766 is the PR I used to address that issue and should be mentioned in the comments.

**Comment by bressler95tops** [comment] 2024-07-02 21:53
I can close this one out since it is already addressed and we don't want to track 2 of the same thing

**Closed** 2024-07-02 21:54 UTC
Labels: OS101 Curriculum: Content Suggestions, Module: 4, Lesson: 1, OS101 Status: Curriculum
